### ISSUE TITLE
[Question] Status of the course

### ISSUE THREAD

**Issue by jaywonchung** [mainmatter/rust-python-interoperability#2]
I am so excited to discover that you're working on this course! Thanks @LukeMathWalker.

I was wondering about the state of this course.
Is it to be considered WIP for now, or would you say people can start digging into the course but maybe expect some rough edges?
Do you have an unofficial timeline in your mind for releasing the course?

**Comment by LukeMathWalker** [comment]
Hey!
The course is done and polished from a content perspective. 

There are some issues with:

- setting up a working Python environment in a way that's reproducible and cross-platform. There are instructions on how to debug certain cases, but there are a few more that came up while running this in a class that we haven't quite found universal solutions for.
- `rye sync`'s behaviour with respect to crates that don't compile (i.e. the exercises you haven't solved yet)

Once those are solved we'll announce more widely, but feel free to be brave and give it a try now if you want to!

**Comment by LukeMathWalker** [comment]
> rye sync's behaviour with respect to crates that don't compile (i.e. the exercises you haven't solved yet)

This has been solved ✅

**Comment by LukeMathWalker** [comment]
All the material has been published and most (known) issues solved. Enjoy!
